/**
 * Telegram Bot API module.
 *
 * Provides core types, client classes ({@link Bot}), update wrapper ({@link Update}),
 * error definitions ({@link TelegramApiError}), and constants/enums ({@link ParseMode}, {@link ChatType}, etc.).
 *
 * @packageDocumentation
 */

export type {
  User,
  Chat,
  ChatPhoto,
  ChatPermissions,
  ChatLocation,
  Message,
  MessageEntity,
  PhotoSize,
  Audio,
  Document,
  Video,
  Animation,
  Voice,
  VideoNote,
  Contact,
  Dice,
  PollOption,
  Poll,
  PollAnswer,
  Location,
  Venue,
  Story,
  MessageOrigin,
  ExternalReplyInfo,
  TextQuote,
  InlineKeyboardButton,
  InlineKeyboardMarkup,
  KeyboardButton,
  ReplyKeyboardMarkup,
  ReplyKeyboardRemove,
  ForceReply,
  ReplyMarkup,
  CallbackQuery,
  InlineQuery,
  ChosenInlineResult,
  ShippingQuery,
  PreCheckoutQuery,
  ChatMemberUpdated,
  ChatMember,
  ChatInviteLink,
  ChatJoinRequest,
  ChatBoostUpdated,
  ChatBoostRemoved,
  BusinessConnection,
  BusinessMessagesDeleted,
  MessageReactionUpdated,
  MessageReactionCountUpdated,
  UserProfilePhotos,
  File,
  WebhookInfo,
  RawUpdate,
  ApiResponse,
  GetUpdatesOptions,
  SendMessageOptions,
  EditMessageTextOptions,
  EditMessageCaptionOptions,
  EditMessageReplyMarkupOptions,
  ChatAction,
  SendPhotoOptions,
  SendAudioOptions,
  SendDocumentOptions,
  SendVideoOptions,
  SendAnimationOptions,
  SendVoiceOptions,
  SendVideoNoteOptions,
  InputMediaPhoto,
  InputMediaVideo,
  InputMediaAnimation,
  InputMediaAudio,
  InputMediaDocument,
  InputMedia,
  SendMediaGroupOptions,
  SendLocationOptions,
  SendVenueOptions,
  SendContactOptions,
  SendPollOptions,
  SendDiceOptions,
  SendChatActionOptions,
  AnswerCallbackQueryOptions,
  InlineQueryResult,
  AnswerInlineQueryOptions,
  PromoteChatMemberOptions,
  CreateChatInviteLinkOptions,
  EditChatInviteLinkOptions,
  SetWebhookOptions,
} from "./types.js";
export { TelegramApiError } from "./types.js";
export * from "./constants.js";
export * from "./bot.js";
export * from "./update.js";

