"""Public namespace for the Bot API 10.3 rich-message types.

The 83 ``Rich*`` and ``InputRich*`` classes are spread over five modules so
that no single module passes the 500-line ceiling: text nodes and buttons in
:mod:`telebot_py.types.rich_text`, received blocks in
:mod:`telebot_py.types.rich_blocks` and :mod:`telebot_py.types.rich_blocks_media`,
outgoing blocks in :mod:`telebot_py.types.rich_blocks_input` and
:mod:`telebot_py.types.rich_blocks_input_media`. This module gathers the whole
public surface in one place so ``telebot_py.types`` can re-export it without
listing 87 imports a second time.
"""

from __future__ import annotations

from telebot_py.types.rich_blocks import (
    RichBlock,
    RichBlockAnchor,
    RichBlockBlockQuotation,
    RichBlockButtons,
    RichBlockCollage,
    RichBlockDetails,
    RichBlockDivider,
    RichBlockExpandableBlockQuotation,
    RichBlockFooter,
    RichBlockList,
    RichBlockListItem,
    RichBlockMathematicalExpression,
    RichBlockParagraph,
    RichBlockPreformatted,
    RichBlockPullQuotation,
    RichBlockSectionHeading,
    RichBlockSlideshow,
    RichBlockTable,
    RichBlockThinking,
    RichMessage,
)
from telebot_py.types.rich_blocks_input import (
    InputRichBlock,
    InputRichBlockAnchor,
    InputRichBlockBlockQuotation,
    InputRichBlockButtons,
    InputRichBlockCollage,
    InputRichBlockDetails,
    InputRichBlockDivider,
    InputRichBlockExpandableBlockQuotation,
    InputRichBlockFooter,
    InputRichBlockList,
    InputRichBlockListItem,
    InputRichBlockMathematicalExpression,
    InputRichBlockParagraph,
    InputRichBlockPreformatted,
    InputRichBlockPullQuotation,
    InputRichBlockSectionHeading,
    InputRichBlockSlideshow,
    InputRichBlockTable,
    InputRichBlockThinking,
    InputRichMessage,
    InputRichMessageContent,
)
from telebot_py.types.rich_blocks_input_media import (
    InputRichBlockAnimation,
    InputRichBlockAudio,
    InputRichBlockDocument,
    InputRichBlockMap,
    InputRichBlockPhoto,
    InputRichBlockVideo,
    InputRichBlockVoiceNote,
    InputRichMessageMedia,
)
from telebot_py.types.rich_blocks_media import (
    RichBlockAnimation,
    RichBlockAudio,
    RichBlockCaption,
    RichBlockDocument,
    RichBlockMap,
    RichBlockPhoto,
    RichBlockTableCell,
    RichBlockVideo,
    RichBlockVoiceNote,
)
from telebot_py.types.rich_text import (
    RichMessageButton,
    RichText,
    RichTextAnchor,
    RichTextAnchorLink,
    RichTextBankCardNumber,
    RichTextBold,
    RichTextBotCommand,
    RichTextButton,
    RichTextCashtag,
    RichTextCode,
    RichTextCustomEmoji,
    RichTextDateTime,
    RichTextEmailAddress,
    RichTextHashtag,
    RichTextItalic,
    RichTextMarked,
    RichTextMathematicalExpression,
    RichTextMention,
    RichTextNode,
    RichTextPhoneNumber,
    RichTextReference,
    RichTextReferenceLink,
    RichTextSpoiler,
    RichTextStrikethrough,
    RichTextSubscript,
    RichTextSuperscript,
    RichTextTextMention,
    RichTextUnderline,
    RichTextUrl,
)

__all__ = [
    "InputRichBlock",
    "InputRichBlockAnchor",
    "InputRichBlockAnimation",
    "InputRichBlockAudio",
    "InputRichBlockBlockQuotation",
    "InputRichBlockButtons",
    "InputRichBlockCollage",
    "InputRichBlockDetails",
    "InputRichBlockDivider",
    "InputRichBlockDocument",
    "InputRichBlockExpandableBlockQuotation",
    "InputRichBlockFooter",
    "InputRichBlockList",
    "InputRichBlockListItem",
    "InputRichBlockMap",
    "InputRichBlockMathematicalExpression",
    "InputRichBlockParagraph",
    "InputRichBlockPhoto",
    "InputRichBlockPreformatted",
    "InputRichBlockPullQuotation",
    "InputRichBlockSectionHeading",
    "InputRichBlockSlideshow",
    "InputRichBlockTable",
    "InputRichBlockThinking",
    "InputRichBlockVideo",
    "InputRichBlockVoiceNote",
    "InputRichMessage",
    "InputRichMessageContent",
    "InputRichMessageMedia",
    "RichBlock",
    "RichBlockAnchor",
    "RichBlockAnimation",
    "RichBlockAudio",
    "RichBlockBlockQuotation",
    "RichBlockButtons",
    "RichBlockCaption",
    "RichBlockCollage",
    "RichBlockDetails",
    "RichBlockDivider",
    "RichBlockDocument",
    "RichBlockExpandableBlockQuotation",
    "RichBlockFooter",
    "RichBlockList",
    "RichBlockListItem",
    "RichBlockMap",
    "RichBlockMathematicalExpression",
    "RichBlockParagraph",
    "RichBlockPhoto",
    "RichBlockPreformatted",
    "RichBlockPullQuotation",
    "RichBlockSectionHeading",
    "RichBlockSlideshow",
    "RichBlockTable",
    "RichBlockTableCell",
    "RichBlockThinking",
    "RichBlockVideo",
    "RichBlockVoiceNote",
    "RichMessage",
    "RichMessageButton",
    "RichText",
    "RichTextAnchor",
    "RichTextAnchorLink",
    "RichTextBankCardNumber",
    "RichTextBold",
    "RichTextBotCommand",
    "RichTextButton",
    "RichTextCashtag",
    "RichTextCode",
    "RichTextCustomEmoji",
    "RichTextDateTime",
    "RichTextEmailAddress",
    "RichTextHashtag",
    "RichTextItalic",
    "RichTextMarked",
    "RichTextMathematicalExpression",
    "RichTextMention",
    "RichTextNode",
    "RichTextPhoneNumber",
    "RichTextReference",
    "RichTextReferenceLink",
    "RichTextSpoiler",
    "RichTextStrikethrough",
    "RichTextSubscript",
    "RichTextSuperscript",
    "RichTextTextMention",
    "RichTextUnderline",
    "RichTextUrl",
]
